# IPPAN Localnet configuration for Node 1 (A)
NODE_ID = "localnet-node1"
VALIDATOR_ID = "1111111111111111111111111111111111111111111111111111111111111111"

# RPC endpoints
RPC_HOST = "127.0.0.1"
RPC_PORT = "3111"

# HTTP P2P networking
P2P_HOST = "127.0.0.1"
P2P_PORT = "4111"
BOOTSTRAP_NODES = "http://127.0.0.1:4112,http://127.0.0.1:4113"
MAX_PEERS = "24"
PEER_DISCOVERY_INTERVAL_SECS = "5"
PEER_ANNOUNCE_INTERVAL_SECS = "15"

# Storage layout
DATA_DIR = "./localnet/node1/data"
DB_PATH = "./localnet/node1/data/db"

# IPNDHT / libp2p settings
FILE_DHT_MODE = "libp2p"
HANDLE_DHT_MODE = "libp2p"
FILE_DHT_LIBP2P_LISTEN = "/ip4/127.0.0.1/tcp/9211"
FILE_DHT_LIBP2P_BOOTSTRAP = "/ip4/127.0.0.1/tcp/9212,/ip4/127.0.0.1/tcp/9213"

# Consensus + DLC knobs
CONSENSUS_MODE = "POA"
ENABLE_DLC = "true"
TEMPORAL_FINALITY_MS = "500"
SHADOW_VERIFIER_COUNT = "3"
MIN_REPUTATION_SCORE = "5000"
REQUIRE_VALIDATOR_BOND = "false"

# RPC development affordances
DEV_MODE = "true"
ENABLE_SECURITY = "false"
LOG_LEVEL = "info"
LOG_FORMAT = "pretty"

# Observability
PROMETHEUS_ENABLED = "false"
