# IPPAN Localnet configuration for Node 2 (B)
NODE_ID = "localnet-node2"
VALIDATOR_ID = "2222222222222222222222222222222222222222222222222222222222222222"

RPC_HOST = "127.0.0.1"
RPC_PORT = "3112"

P2P_HOST = "127.0.0.1"
P2P_PORT = "4112"
BOOTSTRAP_NODES = "http://127.0.0.1:4111,http://127.0.0.1:4113"
MAX_PEERS = "24"
PEER_DISCOVERY_INTERVAL_SECS = "5"
PEER_ANNOUNCE_INTERVAL_SECS = "15"

DATA_DIR = "./localnet/node2/data"
DB_PATH = "./localnet/node2/data/db"

FILE_DHT_MODE = "libp2p"
HANDLE_DHT_MODE = "libp2p"
FILE_DHT_LIBP2P_LISTEN = "/ip4/127.0.0.1/tcp/9212"
FILE_DHT_LIBP2P_BOOTSTRAP = "/ip4/127.0.0.1/tcp/9211,/ip4/127.0.0.1/tcp/9213"

CONSENSUS_MODE = "POA"
ENABLE_DLC = "true"
TEMPORAL_FINALITY_MS = "500"
SHADOW_VERIFIER_COUNT = "3"
MIN_REPUTATION_SCORE = "5000"
REQUIRE_VALIDATOR_BOND = "false"

DEV_MODE = "true"
ENABLE_SECURITY = "false"
LOG_LEVEL = "info"
LOG_FORMAT = "pretty"
PROMETHEUS_ENABLED = "false"
