[package]
name = "ippan-types"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
integration-tests = []

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_bytes = { workspace = true }
hex = { workspace = true }
blake3 = { workspace = true }
rand_core = { workspace = true, features = ["getrandom"] }
time = { workspace = true }
ed25519-dalek = { workspace = true }
thiserror = { workspace = true }
bs58 = { workspace = true }
sha2 = { workspace = true }
bincode = { workspace = true }
ippan-time = { path = "../time" }
