[package]
name = "ippan_economics"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["IPPAN Contributors"]

[dependencies]
serde = { version = "1", features = ["derive" ] }

[dev-dependencies]
rand = "0.8"
